//*****************************************************************************
// Copyright (c) 2014 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
// 
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
// 
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the  
//   distribution.
// 
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This file was automatically generated by the Tiva C Series PinMux Utility
// Version: 1.0.4
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include "Lab_6.h"
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "driverlib/sysctl.h"
#include "driverlib/pin_map.h"
#include "driverlib/rom_map.h"
#include "driverlib/gpio.h"
#include "inc/tm4c123gh6pm.h"

#define	RED_LED  0x02
#define BLUE_LED  0x04
#define GREEN_LED  0x08
//*****************************************************************************
void
PortFunctionInit(void)
{
    //
    // Enable Peripheral Clocks 
    //
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);

    //
    // Enable pin PF0 for GPIOInput
    //

    //
    //First open the lock and select the bits we want to modify in the GPIO commit register.
    //
    HWREG(GPIO_PORTF_BASE + GPIO_O_LOCK) = GPIO_LOCK_KEY;
    HWREG(GPIO_PORTF_BASE + GPIO_O_CR) = 0x1;

    //
    //Now modify the configuration of the pins that we unlocked.
    //
    MAP_GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_0);

    //
    // Enable pin PF3 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_3);

    //
    // Enable pin PF4 for GPIOInput
    //
    MAP_GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_4);

    //
    // Enable pin PF1 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_1);

    //
    // Enable pin PF2 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_2);
		GPIO_PORTF_PUR_R |= 0x01;
		GPIO_PORTF_PUR_R |= 0x10;
}


int main(void){
	int clock;
	//set the system clock to 80MHz
	// SysCtlClockSet(SYSCTL_SYSDIV_2_5|SYSCTL_USE_PLL|SYSCTL_OSC_MAIN|SYSCTL_XTAL_16MHZ);
	
	
	// SysCtlDelay(3); //each value inside this function delays for 3 clock cycle, so with the value of 3, it delays it for 9 clock cycle
	
	
	clock = SysCtlClockGet(); //by default, clock = 16000000
	
	
  //initialize the GPIO ports 
	PortFunctionInit();
	
	
	//
	// Loop forever
	//
	while(1){
		
		//if SW1 is pressed
		if(GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_4)== 0x00) 
		{
			
			  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, GREEN_LED); //turn green LED on
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x00); //the red LED is off
				
			//while green is on
				while(1){ 
						
					
						// Delay for a bit.
					//	SysCtlDelay(13333333/2);	// 8Mhz/3 cycles = 2666666 seconds is half a second
					SysCtlDelay(SysCtlClockGet()/6);
										//
										//
										// delay = 0.5/((1/80MHz)*3) = 13333333 
										//
										//
					//	clock = SysCtlClockGet();

						
						// Toggle the green LED.
						GPIO_PORTF_DATA_R ^=GREEN_LED; 
							
									//if SW1 is not pressed
									if(GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_4)== 0x10)
									{
										break; //stops toggling
									}
									
									//if SW2 is pressed
									if(GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_0)== 0x00)
									{
										
										GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x00);  //the red LED is off
										GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, 0x00);  //the green LED is off
									}
				}//end of green toggle
		}
		else //if SW1 is not pressed
		{
		    GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, 0x00);     //turn green LED off
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, RED_LED);  //the red LED is on	
			
			//while red is on
				while(1){ 
			
						// Delay for a bit.
						SysCtlDelay(13333333/2);	 //4000000 clock cycle = 1 second, so 2000000 clock cycle = 0.5 second
							

						// Toggle the LED.
						GPIO_PORTF_DATA_R ^=RED_LED; 
					
							
									//if SW1 is pressed
									 if(GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_4)==0x00)  
										{
												 break;      //stops toggling
										} 
										
									//if SW2 is pressed	
									 if (GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_0) == 0x00)     
										{    
												 GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x00);     // red LED off
										}			
		 }//end of red toggle
		}
	} //end of while loop	
}//end of main program
