//*****************************************************************************
// Copyright (c) 2014 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
// 
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
// 
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the  
//   distribution.
// 
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This file was automatically generated by the Tiva C Series PinMux Utility
// Version: 1.0.4
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "L8.h"
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "driverlib/sysctl.h"
#include "driverlib/pin_map.h"
#include "driverlib/rom_map.h"
#include "driverlib/gpio.h"
#include "driverlib/timer.h"
#include "driverlib/interrupt.h"
#include "inc/tm4c123gh6pm.h"

#define 	RED 		0x02
#define 	BLUE 		0x04
#define 	GREEN		0x08
//*****************************************************************************

// global variable visible in Watch window of debugger
// increments at least once per button press
volatile unsigned long count = 0;
int clock;

void
PortFunctionInit(void)
{
    //
    // Enable Peripheral Clocks 
    //
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);

    //
    // Enable pin PF0 for GPIOInput
    //

    //
    //First open the lock and select the bits we want to modify in the GPIO commit register.
    //
    HWREG(GPIO_PORTF_BASE + GPIO_O_LOCK) = GPIO_LOCK_KEY;
    HWREG(GPIO_PORTF_BASE + GPIO_O_CR) = 0x1;

    //
    //Now modify the configuration of the pins that we unlocked.
    //
    MAP_GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_0);
	

    //
    // Enable pin PF3 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_3);

    //
    // Enable pin PF4 for GPIOInput
    //
    MAP_GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_4);

    //
    // Enable pin PF1 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_1);

    //
    // Enable pin PF2 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_2);
		
	GPIO_PORTF_PUR_R |= 0x11;
}


//Globally enable interrupts 
void IntGlobalEnable(void)
{
    __asm("    cpsie   i\n");
}

void Timer0A_Init(unsigned long period)
{   
	//volatile uint32_t ui32Loop; 
	//
  // Enable Peripheral Clocks 
  //
	
  SysCtlPeripheralEnable(SYSCTL_PERIPH_TIMER0);
  TimerConfigure(TIMER0_BASE, TIMER_CFG_PERIODIC); 		// configure for 32-bit timer mode
  TimerLoadSet(TIMER0_BASE, TIMER_A, period -1);      //reload value
	IntPrioritySet(INT_TIMER0A, 0x00);  	 // configure Timer0A interrupt priority as 0
  IntEnable(INT_TIMER0A);    				// enable interrupt 19 in NVIC (Timer0A)
	TimerIntEnable(TIMER0_BASE, TIMER_TIMA_TIMEOUT);      // arm timeout interrupt
  TimerEnable(TIMER0_BASE, TIMER_A);      // enable timer0A
	
	
	//SYSCTL_RCGC1_R |= SYSCTL_RCGC1_TIMER0; // activate timer0
  //ui32Loop = SYSCTL_RCGC1_R;				// Do a dummy read to insert a few cycles after enabling the peripheral.
  //TIMER0_CTL_R &= ~0x00000001;     // disable timer0A during setup
  //TIMER0_CFG_R = 0x00000000;       // configure for 32-bit timer mode
  //TIMER0_TAMR_R = 0x00000002;      // configure for periodic mode, default down-count settings
  //TIMER0_TAILR_R = period-1;       // reload value
	//NVIC_PRI4_R &= ~0xE0000000; 	 // configure Timer0A interrupt priority as 0
  //NVIC_EN0_R |= 0x00080000;     // enable interrupt 19 in NVIC (Timer0A)
	//TIMER0_IMR_R |= 0x00000001;      // arm timeout interrupt
  //TIMER0_CTL_R |= 0x00000001;      // enable timer0A
}

//interrupt handler for Timer0A
void Timer0A_Handler (void)
{
    // acknowledge flag for Timer0A timeout
		//TimerIntClear(TIMER0_BASE, TIMER_TIMA_TIMEOUT);
		TIMER0_ICR_R |= 0x00000001; 
		// Increments counter by 1
    count ++;
		count = count&7;
}  


/** INTERRUPT CONFIGURATION***/
void Interrupt_Init(void)
{
  NVIC_EN0_R |= 0x40000000;  		// enable interrupt 30 in NVIC (GPIOF)
	//NVIC_PRI7_R &= 0x00E00000; 		// configure GPIOF interrupt priority as 0
	IntPrioritySet(INT_GPIOF, 0x02);
	GPIO_PORTF_IM_R |= 0x11;   		// arm interrupt on PF0 and PF4
	GPIO_PORTF_IS_R &= ~0x11;     // PF0 and PF4 are edge-sensitive
  GPIO_PORTF_IBE_R &= ~0x11;   	// PF0 and PF4 not both edges trigger 
	GPIO_PORTF_IEV_R &= ~0x11;  	// PF0 and PF4 falling edge event
	IntGlobalEnable();        		// globally enable interrupt
}

//interrupt handler
void GPIOPortF_Handler(void)
{
	
	
	//switch debounce
	NVIC_EN0_R &= ~0x40000000; 
	for(int i = 0; i <10000; i++)
	{
		SysCtlDelay(53333);	// Delay for a while
	}
	NVIC_EN0_R |= 0x40000000; 
	
	//SW1 has action
	if(GPIO_PORTF_RIS_R&0x10)
	{
		// acknowledge flag for PF4
		GPIO_PORTF_ICR_R |= 0x10; 
		
		//SW1 is pressed
		if((GPIO_PORTF_DATA_R&0x10)==0x00) 
		{
			//counter imcremented by 1
			count++;
			count=count&7;
		}
	}
	
	//SW2 has action
  if(GPIO_PORTF_RIS_R&0x01)
	{
		// acknowledge flag for PF0
		GPIO_PORTF_ICR_R |= 0x01; 
		
		//if((GPIO_PORTF_DATA_R&0x01)==0x00) 
		//{
			//counter imcremented by 1
			count--;
			count=count&7;
			
		//}
	}
	
	
}
	
	int main(void)
{
	unsigned long period = 40000000;
		SysCtlClockSet(SYSCTL_SYSDIV_5|SYSCTL_USE_PLL|SYSCTL_XTAL_16MHZ|SYSCTL_OSC_MAIN);
    clock = SysCtlClockGet();
	
	
		//initialize the GPIO ports	
		PortFunctionInit();
		
		//configure the GPIOF interrupt
		Interrupt_Init();
	
	    
    //initialize Timer0A and configure the interrupt
    Timer0A_Init(period);
	


    
    //
    // Loop forever.
    //
    while(1)
    {
			switch (count)
			{
				case 0:
           GPIO_PORTF_DATA_R &= ~RED;
           GPIO_PORTF_DATA_R &= ~BLUE;            
           GPIO_PORTF_DATA_R &= ~GREEN;
           break; 
				case 1:
           GPIO_PORTF_DATA_R |=  RED;
           GPIO_PORTF_DATA_R &= ~BLUE;            
           GPIO_PORTF_DATA_R &= ~GREEN;
           break;
				case 2:
           GPIO_PORTF_DATA_R &= ~RED;
           GPIO_PORTF_DATA_R |= BLUE;            
           GPIO_PORTF_DATA_R &= ~GREEN;
           break;
				case 3:
           GPIO_PORTF_DATA_R |= RED;
           GPIO_PORTF_DATA_R |= BLUE;            
           GPIO_PORTF_DATA_R &= ~GREEN;
           break;
				case 4:
           GPIO_PORTF_DATA_R &= ~RED;
           GPIO_PORTF_DATA_R &= ~BLUE;            
           GPIO_PORTF_DATA_R |= GREEN;
           break;
				case 5:
           GPIO_PORTF_DATA_R |= RED;
           GPIO_PORTF_DATA_R &= ~BLUE;            
           GPIO_PORTF_DATA_R |= GREEN;
           break;
				case 6:
           GPIO_PORTF_DATA_R &= ~RED;
           GPIO_PORTF_DATA_R |= BLUE;            
           GPIO_PORTF_DATA_R |= GREEN;
           break;
				case 7:
           GPIO_PORTF_DATA_R |= RED;
           GPIO_PORTF_DATA_R |= BLUE;            
           GPIO_PORTF_DATA_R |= GREEN;
           break;


					
    }
}
	
	
}
